# device_url: now set by launch file argument
# world_frame: now set by launch file argument
  
general:
  octomap_reset_before_takeoff: true
  octomap_reset_timeout: 3.0 # [s]
  control_update_rate: 20.0 # [Hz]
  diagnostics_publish_rate: 1.0 # [Hz]

takeoff:
  height: 1.0 # [m]
  position_samples: 20 # before takeoff, the first waypoint will be set to the average of these samples

px4:
  target_velocity: 1.5 # [m/s]
  waypoint_loiter_time: 0.0 # [s]
  waypoint_acceptance_radius: 0.6 # [m]
  altitude_acceptance_radius: 0.5 # [m]

mavsdk:
  logging_print_level: 2 # 0 - Debug, 1 - Info, 2 - Warning, 3 - Error
  logging_filename: "mavsdk.log"
  yaw_offset_correction: -1.5708 # [rad] NOTE: MAVSDK 0.42 represents yaw=0 as heading aligned with Y axis. We want to align with X axis at yaw=0
  mission_upload_attempts_threshold: 5
