# device_url: "serial:///dev/ttyS7:921600"
device_url: "udp://:14590"
takeoff_height: 1.0 # [m]
reset_octomap_before_takeoff: true
waypoint_marker_scale: 0.3
yaw_offset_correction: -1.5708 # [rad] NOTE: MAVSDK 0.42 represents yaw=0 as heading aligned with Y axis. We want to align with X axis at yaw=0
takeoff_height: 1.0 # [m]
reset_octomap_before_takeoff: true
waypoint_marker_scale: 0.3
waypoint_loiter_time: 0.0 # [s]
waypoint_acceptance_radius: 0.2 # [m]
target_velocity: 1.5 # [m/s]
control_update_rate: 20.0 # [Hz]
takeoff_position_samples: 20 # before takeoff, the first waypoint will be set to the average of these samples
