param_namespace:
  # device_url: "serial:///dev/ttyS7:921600"
  device_url: "udp://:14540"
  takeoff_height: 1.0 # [m]
  reset_octomap_before_takeoff: true
  waypoint_marker_scale: 0.3
  waypoint_loiter_time: 0.0 # [s]
  waypoint_acceptance_radius: 0.2 # [m]
  target_velocity: 0.7 # [m/s]
